### ISSUE TITLE
BUG: `A.reduce_scalar(agg.count)` breaks when `A.shape = (0, 0)`

### ISSUE THREAD

**Issue by ParticularMiner** [metagraph-dev/grblas#168] opened 2022-03-08 10:21 UTC
The bug may be reproduced by running the following code:
```python
import grblas as gb


A = gb.Matrix.new(int)
A.reduce_scalar(gb.agg.count)
```

Python segfaults and exits without raising an exception.

**Comment by eriknw** [comment] 2022-03-08 19:44
Wow, that's impressive.  Confirmed.  I think this might be a bug in SuiteSparse:GraphBLAS.  I'm able to reproduce segfaults with matrix multiplies.  I'll share more details after lunch.  It's really weird.

Relatedly (but not the cause), I wonder if using `size=1` here will give issues with empty inputs: https://github.com/metagraph-dev/grblas/blob/4d9f31edeb17a261198b7e7ccebf8923701ca751/grblas/_agg.py#L190

Thanks @ParticularMiner!

**Comment by DrTimothyAldenDavis** [comment] 2022-03-08 23:33
I've replicated the bug.  I think I know what's happening; hopefully it will be a quick fix.

**Comment by DrTimothyAldenDavis** [comment] 2022-03-08 23:45
Good catch.  That is definitely a SuiteSparse:GraphBLAS bug.  I have a draft fix for it that I need to validate and run all my tests with: https://github.com/DrTimothyAldenDavis/GraphBLAS/commit/1428379dfe045fb1d91ac268195889bd97f1c12e

**Comment by DrTimothyAldenDavis** [comment] 2022-03-09 03:05
Fixed in SuiteSparse:GraphBLAS v6.2.4.

**Comment by ParticularMiner** [comment] 2022-03-09 11:25
That was quick!  

I'm yet to test the fix myself.  But in the meantime, many thanks @eriknw and @DrTimothyAldenDavis for fixing this!

**Comment by eriknw** [comment] 2022-03-10 06:05
This is fixed!  Thanks all.

To get the fix, install `python-suitesparse-graphblas` version 6.2.4.0 via conda.

**Closed by eriknw** 2022-03-10 06:05 UTC
